version: 2.1
executors:
  default:
    working_directory: ~/circleci-books-app
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          PGUSER: circleci-books_app
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: circleci-books-app
          POSTGRES_DB: books-app

commands:
  set_up:
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1

      - run:
          name: Install Bundle
          command: gem install bundle

      - run:
          name: Bundle Install
          command: bundle install

      - save_cache:
          key: gem-chace-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-chace-v1-{{ checksum "yarn.lock" }}
            - yarn-chace-v1-

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: yarn-chace-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  minitest:
    executor: default
    environment:
      RAILS_ENV = test
    steps:
      - checkout
      - set_up
      - run:
          name: Database setup
          command: bin/rails db:schema:load

      - run:
          name: Run test
          command: bin/rails test

  deploy:
    executor: default
    steps:
      - checkout
      - set_up
      - add_ssh_keys:
          fingerprints:
            - "4d:e8:26:23:96:bf:6c:6e:15:b8:a8:25:0c:21:8e:f5"
      - run:
          name: deploy
          command: bundle exec cap production deploy

workflows:
  minitest-deploy:
    jobs:
      - minitest:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - minitest
          filters:
            branches:
              only: master
