version: 2.1
jobs:
  build:
    working_directory: ~/circleci-books-app
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-books_app
          RAILS_ENV: test
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: circleci-books-app
          POSTGRES_DB: books-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1

      - run:
          name: Install Bundle
          command: gem install bundle

      - run:
          name: Bundle Install
          command: bundle install

      - save_cache:
          key: gem-chace-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-chace-v1-{{ checksum "yarn.lock" }}
            - yarn-chace-v1-

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: yarn-chace-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Database setup
          command: bin/rails db:schema:load

      - run:
          name: Run test
          command: bin/rails test
