version: 2.1
executors:
  default:
    working_directory: ~/circleci-books-app
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          PGUSER: circleci-books_app
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: circleci-books-app
          POSTGRES_DB: books-app

jobs:
  build:
    executor: default
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1

      - run:
          name: Install Bundle
          command: gem install bundle

      - run:
          name: Bundle Install
          command: bundle install

      - save_cache:
          key: gem-chace-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-chace-v1-{{ checksum "yarn.lock" }}
            - yarn-chace-v1-

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: yarn-chace-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - add_ssh_keys:
          fingerprints:
            - "6d:d8:b3:ca:12:5f:ea:18:fa:6b:50:7d:d9:7e:d3:48"

  minitest:
    executor: default
    environment:
      RAILS_ENV = test
    steps:
      - run:
          name: Database setup
          command: bin/rails db:schema:load

      - run:
          name: Run test
          command: bin/rails test

  deploy:
    executor: default
    steps:
      - run:
          name: deploy
          command: bundle exec cap production deploy

workflows:
  build-minitest-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - minitest:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - minitest
          filters:
            branches:
              only: master
